<a href="https://colab.research.google.com/github/aditi884/lab-/blob/main/Aditi_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
a=np.array([[[1,2],[2,4]],[[1,2],[3,4]]])
print(a)
print(a.ndim) #dimension
print(a.shape) #rows and cols and matrix as well if needed
print(a.dtype) #data type  int64>int >U3> for string  >U32> for mixed
b=np.zeros([1,3]) # print 0
print(b)
c=np.ones([4,5]) #print 1
print(c)
d=np.eye(5) #identity matrix
print(d)
e=np.arange(1,10,2) #start stop step
print(e)
f=np.linspace(0,10,5) #count value, stop value, value to split
print(f)        #0      1
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,1]) #indexing
print(arr[:,2]) #slicing
print(arr.reshape(3,2)) #reshape the array
print(arr.flatten()) #flat the matrix to 1D

A=np.array([1,2,3])
B=np.array([4,5,6])
print(A+B)
print(A*B)
#broadcasting
C=np.array([[1],[2],[3]]) #like a multipication of matrix
D=np.array([10,20,30])
print(C+D)

ar=np.array([[1,2],[3,4]])
print(ar.sum())
print(ar.mean())
print(ar.max(axis=0))  #0-> rows  1->cols
print(np.median(ar))

t=np.array([1,2,3,4,5])
mask=t>3
print(t[mask])  #filter the nember grater than 3

[[[1 2]
  [2 4]]

 [[1 2]
  [3 4]]]
3
(2, 2, 2)
int64
[[0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1 3 5 7 9]
[ 0.   2.5  5.   7.5 10. ]
5
[3 6]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[5 7 9]
[ 4 10 18]
[[11 21 31]
 [12 22 32]
 [13 23 33]]
10
2.5
[3 4]
2.5
[4 5]
